---
- block:
  - name: create prometheus group account
    group:
      name: prometheus
      system: yes
      state: present
  - name: create prometheus user account
    user:
      name: prometheus
      group: prometheus
      system: yes
      shell: "/bin/false"
      state: present
  - name: fetch mysqld exporter tar file and extract it to destination
    unarchive:
      src: "https://github.com/prometheus/mysqld_exporter/releases/download/v{{ mysqld_exporter_version }}/mysqld_exporter-{{ mysqld_exporter_version }}.linux-amd64.tar.gz"
      dest: "/tmp"
      remote_src: yes
  - name: move mysqld exporter package to final destination
    command:
      cmd: "mv /tmp/mysqld_exporter-{{ mysqld_exporter_version }}.linux-amd64 {{ mysqld_exporter_base_dir }}"
      creates: "{{ mysqld_exporter_base_dir }}"
  - name: setup file permissions
    file:
      path: "{{ mysqld_exporter_base_dir }}"
      state: directory
      recurse: yes
      owner: prometheus
      group: prometheus
      mode: "o-rwx"
  - name: setup mysqld exporter config file
    template:
      src: "mysqld_exporter.cnf"
      dest: "{{ mysqld_exporter_base_dir }}/mysqld_exporter.cnf"
      owner: prometheus
      group: prometheus
      mode: "0660"
  - name: install mysqld_exporter systemd service file
    template:
      src: "mysqld_exporter.service"
      dest: "/etc/systemd/system/mysqld_exporter.service"
      owner: root
      group: root
      mode: "0644"
  - name: setup mysqld_exporter systemd service
    systemd:
      name: "mysqld_exporter.service"
      daemon_reload: yes
      enabled: yes
      state: restarted
  tags:
    - mysqld_exporter
